### ISSUE TITLE
左上角的扫码功能

### ISSUE THREAD

**Issue by ult-zhiwei** [ultiledger/utoken#10]
左上角的扫码功能，点击无效，无任何提示，设置中，打开相机权限，可以用，建议添加提示。

**Comment by chenxukf103** [comment]
一般第一次进去app的时候会询问是否“允许XXX权限”，如果选择了“否”并且勾选不在提示，是不会提示的了，很多app应该都是这样的。你第一次打开app的时候有询问吗？

**Comment by liangran** [comment]
我安装时有提示。

**Comment by ult-zhiwei** [comment]
> 
> 
> 一般第一次进去app的时候会询问是否“允许XXX权限”，如果选择了“否”并且勾选不在提示，是不会提示的了，很多app应该都是这样的。你第一次打开app的时候有询问吗？

后面用户再去点击，可以提示让用户自己去打开权限吗？

**Comment by chenxukf103** [comment]
可以加个提示
