### ISSUE TITLE
1.3.3得ripplelib 挂单会失败

### ISSUE THREAD

**Issue by ult-zhiwei** [ultiledger/utoken#109]
ValidationError: Serialized transaction does not match original txJSON
原因可能和value有关系
value如果末尾有0会失败，钱包这边处理得时候末尾应该多了0，就失败了

**Comment by ult-zhiwei** [comment]
toFixed()会在末尾补零

**Comment by yxxyun** [comment]
可能是，我这边只测试了位数多的情况，位数不足的没有测试，所以没发现。应该是原始的txjson的数值补了零，签名后的tx，ripple-lib又解码回去和原始的txjson作了比较，解码的时候没有补零，所以不一致了报错。
