### ISSUE TITLE
XRP转账，输入转账密码后显示账号余额过低，转账失败（建议提示下什么资产余额过低）

### ISSUE THREAD

**Issue by wudenggang0** [ultiledger/utoken#12]
如题，建议说明下需要什么资产的最低余额。如果是XLM的最低余额的话，这个软件就没有什么存在的意义。
![default](https://user-images.githubusercontent.com/3587832/50159091-c4586c00-0310-11e9-8b28-5fb7ba9a82af.png)

**Comment by wudenggang0** [comment]
![1](https://user-images.githubusercontent.com/3587832/50222112-35138d00-03d2-11e9-86ab-b199e8f9c593.jpg)
使用的是导入的XRP账户，里面有30个XRP，交易5个XRP。错误显示画面如图。

**Comment by ult-zhiwei** [comment]
> 
> 
> ![1](https://user-images.githubusercontent.com/3587832/50222112-35138d00-03d2-11e9-86ab-b199e8f9c593.jpg)
> 使用的是导入的XRP账户，里面有30个XRP，交易5个XRP。错误显示画面如图。

瑞波网络最少冻结20xrp, 这个20个是转不出去的; 每个信任线会冻结5个，每个挂单也会冻结5个 取消信任和挂单会解冻，是你的XRP可用余额不足了，钱包这边会优化下显示 显示下冻结的金额
