### ISSUE TITLE
有手续费的IOU转账失败

### ISSUE THREAD

**Issue by yxxyun** [ultiledger/utoken#131]
比如gatehub的IOU，转账会失败，报tecPATH_PARTIAL

原因是sendmax 和 sendamount设置了相同的值。

https://github.com/ultiledger/utoken/blob/dev/src/wallet/coins/Ripple.js#L227

**Comment by ult-zhiwei** [comment]
那是不是要查询下该IOU有没有手续费，然后设置sendmax,
