### ISSUE TITLE
软件升级时，如果不打开网站下载新软件，只是从软件本身下载时无法更新

### ISSUE THREAD

**Issue by wudenggang0** [ultiledger/utoken#16]
登录软件，有新版要升级时，选择更新软件，更新完成后安装时显示解析包时错误（显示：解析错误，实际软件包没有下载完成）。手机为荣耀V10，后续从网站手动下载软件后覆盖安装可行。但后续版本升级时不知道会不会同样问题。
![3-2](https://user-images.githubusercontent.com/3587832/50400272-67513000-07c0-11e9-8ae5-953bf78bb65e.jpg)

![3-1](https://user-images.githubusercontent.com/3587832/50400274-6cae7a80-07c0-11e9-82bb-1faaddcf14da.jpg)

**Comment by chenxukf103** [comment]
1.1.6修复该问题，旧版如果无法更新请到官网下载覆盖更新即可
