### ISSUE TITLE
BTC的余额显示的精度是7位，和恒星的一样了

### ISSUE THREAD

**Issue by imloama** [ultiledger/utoken#4]

**Comment by chenxukf103** [comment]
目前余额精度都是最多保留7位

**Comment by ult-zhiwei** [comment]
可以具体点吗，或者上传一个截图

**Comment by imloama** [comment]
![image](https://user-images.githubusercontent.com/3024323/50062682-667a3600-01e3-11e9-955c-e9082bc53df8.png)
实际余额是:0.00001466，不是0.0000147

**Comment by liangran** [comment]
1, BTC的精度是8位。
2, XLM的精度是7位。
3, XRP的精度是6位。

如果是JS的话，应该自己写一个round的方法，而不是用toFixed。round到8位应该就能解决上面3个的精度问题。

function round(dight, howMany) {
	if(howMany) {
		dight = Math.round(dight * Math.pow(10, howMany)) / Math.pow(10, howMany);
	} else {
		dight = Math.round(dight);
	}	
	return dight;
}

**Comment by ult-zhiwei** [comment]
要不都round 8位
