### ISSUE TITLE
交易- 挂单数量的小数点位数限制成6位，多了会挂单失败。

### ISSUE THREAD

**Issue by ult-zhiwei** [ultiledger/utoken#62]

**Comment by yxxyun** [comment]
https://github.com/ripple/ripple-lib/releases/tag/1.3.0

看样子升级到1.3.0以上能解决这个问题，不知道这个问题以前是怎么解决的？

**Comment by yxxyun** [comment]
刚看了下是限制了输入的位数，现在可以通过升级ripple lib版本来解决了。
