### ISSUE TITLE
[瑞波]转账历史获取修改

### ISSUE THREAD

**Issue by ult-zhiwei** [ultiledger/utoken#75]
获取最近历史，获取更多按钮功能优化，本地缓存优化。

**Comment by ult-zhiwei** [comment]
修改逻辑：
this.api = new RippleAPI(xxx);

const options = {
	account: address,
	limit: 20
  }
const command = "account_tx";

let rsp = await this.api.request(command, options);

let hasNext = this.api.hasNextPage(rsp);

rsp2 = await this.api.requestNextPage(command, options, rsp);

rsp+rsp2

filter: tx.TransactionType == "Payment" 

format: 
       {
			"hash":txn.tx.hash,
			"date":(txn.tx.date + 0x386D4380) * 1000,
			"TransactionType":txn.tx.TransactionType,
			"Account":txn.tx.Account,
			"Destination":txn.tx.Destination,
			"DestinationTag":txn.tx.DestinationTag,
			"delivered_amount":amount,
			"inLedger":txn.tx.inLedger,
			"status":0,
		}

**Comment by ult-zhiwei** [comment]
delivered_amount= txn.meta.delivered_amount

**Comment by yxxyun** [comment]
也可以考虑使用dataApi
https://xrpl.org/data-api-v2-tool.html#get-account-transaction-history

**Comment by yxxyun** [comment]
分页使用 marker 
https://xrpl.org/data-api.html#pagination
缺点是 dataAPI有rate limit

rippleApi的缺点是大部分rippled服务器都不保存全历史记录
