### ISSUE TITLE
添加基于ilp的币种互换服务

### ISSUE THREAD

**Issue by yxxyun** [ultiledger/utoken#92]
参考https://github.com/Kava-Labs/switch

**Comment by ult-yole** [comment]
参考的项目类似闪兑，那这个汇率是已什么为基准的？
ilp是否有更多资料

**Comment by yxxyun** [comment]
详细资料见 https://github.com/Kava-Labs/ilp-sdk
需要自己搭建 ILP-connector，一个基于layer 2的做市商的角色。
